import type { Metadata } from 'next'
import './globals.css'
import { db } from '@/db/drizzle'
import { users } from '@/db/schema'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
}

export default async function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body>{children}</body>
        </html>
    )
}
